### ISSUE TITLE
Get rid of telcons.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/charter-webperf#18]

**Comment by igrigorik** [comment]
Why? Is there a particular concern and something we should address about the current format?

**Comment by Ms2ger** [comment]
See the thread around https://lists.w3.org/Archives/Public/public-web-perf/2015May/0022.html for one recent example; it simply is no longer a sensible approach to decision making.

**Comment by igrigorik** [comment]
Complications in scheduling are not a good nor sufficient reason to cease telecons.

**Comment by tobint** [comment]
I'll just add here that while having the teleconferences do help facilitate clearer communication, we rarely if ever have made direct decisions on the teleconferences without first communicating the discussion points (through teleconference notes we send out) as well as asking direct questions about those subjects on the list. We have even taken questions in advance from people who could not attend the conference call, but wanted a point discussed.

**Comment by plehegar** [comment]
I believe we should adopt the async decision text, such as
[[
 As explained in the W3C Process Document (section 3.3), this group will seek to make decisions when there is consensus and with due process. The expectation is that typically, an editor or other participant makes an initial proposal, which is then refined in discussion with members of the group and other reviewers, and consensus emerges with little formal voting being required. However, if a decision is necessary for timely progress, but consensus is not achieved after careful consideration of the range of views presented, the Chairs should put a question out for voting within the group (allowing for remote asynchronous participation -- using, for example, email and/or web-based survey techniques) and record a decision, along with any objections. The matter should then be considered resolved unless and until new information becomes available.

Any resolution taken in a face-to-face meeting or teleconference is to be considered provisional until 10 working days after the publication of the resolution in draft minutes sent to the working groups mailing list. If no objections are raised on the mailing list within that time, the resolution will be considered to have consensus as a resolution of the Working Group.

This charter is written in accordance with Section 3.4, Votes of the W3C Process Document and includes no voting procedures beyond what the Process Document requires. 
]]
from http://www.w3.org/2014/secondscreen/charter#decisions

**Comment by plehegar** [comment]
Additional information relevant here btw:
[[
The way the working group operates in discussion terms seems to largely be through telecons.  github issues are used some, but you have to know about them to pay attention to them, and they don't seem to be a common discussion venue anyway.  The mailing list seems to be a bit of an afterthought, and it's not uncommon for mails to the list to be completely ignored by the editors of the relevant specifications. They've gotten a bit better on this front, but this is one of my main problems with this working group. 
]]
https://groups.google.com/d/msg/mozilla.dev.platform/dH_g8sq4740/1ZjIg70hVIgJ

**Comment by toddreifsteck** [comment]
My 2 cents:
All updates to the specs are made via GitHub. This means that feedback and history is visible and tracked in a public venue. If a decision is made and adopted, a new issue can always be opened to track a disagreement and the group is always ready to evaluate alternative pull requests.

Given the open nature of the specs and issues, I am not clear that any decision is final until adopted by all user agents and the web.

Given that operating environment, a 10 day waiting period seems unnecessary. if a mistake is made, a new issue can be raised.

**Comment by toddreifsteck** [comment]
And although it is my believe the 10 day period is not generally necessary, it also does not block forward progress and we could adopt it quite easily.

**Comment by wayneca** [comment]
The reason for making decisions at meetings tentative is the global participation in W3C.  Any telecon is going to be in the middle of the night in some part of the world, making it difficult for people to attend.  It's also expensive to attend face to face meetings, and if English is a second language it can be difficult to respond immediately in a meeting..  So, a paragraph like that is being commonly adopted.   Charters that include this vary in how long the period is.  7 days is reasonable - it's just enough time to give people a chance to see the minutes.   The group goes ahead and makes whatever change so there isn't any delay, but if someone objects, they reopen it.  It could be the group already does that, but having it in the Charter guarantees it.  So, there's an effort by some of us to get wording like that in all WG Charters.

**Comment by igrigorik** [comment]
sgtm.

**Comment by toddreifsteck** [comment]
Good points, @wcarr. Thanks for the background. Sounds good to me as well.

**Comment by plehegar** [comment]
See proposed wording in the pull request

**Comment by toddreifsteck** [comment]
Updated wording has been added to charter. Closing issue.
