### ISSUE TITLE
Shut down the webperf wg, move all specs to webapps.

### ISSUE THREAD

**Issue by Ms2ger** [w3c/charter-webperf#19]
This group completely fails to produce implementable specifications or even reply to review comments. I don't see how this group will ever produce useful specifications, so I believe it would be better to shut it down now, rather than waste any more time trying to run it.

**Comment by igrigorik** [comment]
I'm sorry you feel that way. Can you highlight particular issues that we should investigate?

The "lack of useful / implementable specifications" is not true. Just from the more recently published specs: NEL, Resource Hints, Preload, Frame Timing, and others, are all being implemented in Chrome; FF is implementing Resource Hints, Frame Timing; IE team has given positive signals on all the same specs.

**Comment by plehegar** [comment]
A few things to add as well:
- as @igrigorik noted, there are implementations, even if the pace is as fast as I wished. A good recent evidence is the feedback we're receiving on Frame Timing tests:
  https://lists.w3.org/Archives/Public/public-web-perf/2015Jun/0075.html
  There was also a recent thread on public-web-perf with Boris on what we can do to better informed implementers.
- In the past, we used to drop comments way too often. We are still slow at addressing comments indeed but we switched all of our specs to github to ensure proper tracking. See http://www.w3.org/2010/webperf/board/. It's not clear that switching the deliverables into webapps would improve our processing rate of issues. See for example the https://github.com/w3c/page-visibility/issues/1 . Any help is welcome.
- if moved into webapps, it would likely end up as a task force, so I'm not sure we would gain significant time to what we have today. There is a bit of overhead in having the webperf group but I wouldn't claim it to be significant.
- so far, the organizations behind the webperf group are supportive of continuing the Group. You may not deem this as significant for you but that's still a data point nevertheless.

**Comment by plehegar** [comment]
At this point, it's unlikely the Group will get closed, so closing this issue. I will note however that we did stress the need to get proper reviews from WebApps in the new charter. See
 https://github.com/w3c/charter-webperf/commit/f2a6d3f97a57b529898ab0a099118f3547f4bc25
