### ISSUE TITLE
 Deliverables and their interrelationships are a bit of a mess. 

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-webperf#21]
[[
The deliverables and their interrelationships are a bit of a mess. 
See the thread I started at 
https://lists.w3.org/Archives/Public/public-web-perf/2015Jun/0057.html. 
I would like the working group to explicitly pursue addressing those issues. 
]]
https://groups.google.com/d/msg/mozilla.dev.platform/dH_g8sq4740/1ZjIg70hVIgJ

**Comment by plehegar** [comment]
Proposed wording in pull request

**Comment by toddreifsteck** [comment]
Given that we've updated commitment in charter, closing this issue for now.
