### ISSUE TITLE
Workers support and mapping timelines

### ISSUE THREAD

**Issue by plehegar** [w3c/charter-webperf#22]
[[
I think there should be something explicit in the 
deliverables about extending the various APIs involved to workers and 
about making it possible to map timestamps between timelines in 
different globals.  This is already being worked on actively, so should 
not be controversial, but should be a bit more specific than just 
"incremental revisions to a bunch of specs".
]]
https://groups.google.com/d/msg/mozilla.dev.platform/dH_g8sq4740/1ZjIg70hVIgJ

**Comment by igrigorik** [comment]
We did add "In addition, the Working Group will review the specifications listed above to take into account background scripts and persistent background processing, provided by Web Worker and Service Worker." Should we make that stronger?

**Comment by plehegar** [comment]
Proposed wording in pull request

**Comment by toddreifsteck** [comment]
Given the update to language, closing this issue for now.

**Comment by plehegar** [comment]
The change should have been:
[[
extend its deliverables to take into account background scripts and persistent background processing, provided by Web Worker and Service Worker, and provide the ability to map timelines in different globals.
]]
