### ISSUE TITLE
Expose Memory Pressure API?

### ISSUE THREAD

**Issue by igrigorik** [w3c/charter-webperf#33]
(discussed at TPAC 2016; rough notes and summary of discussed ideas below)
- We discussed @mounirlamouri's [Memory Pressure proposal](https://github.com/mounirlamouri/memory-pressure-api/) at the June F2F. Since then, rniwa@ ran an initial security/privacy review within Apple.. first pass: thumbs up.
- Some API nitpicks and suggestions discussed at TPAC:
  - We probably want to rename to { low → high → critical }
    - Q: need to investigate differences between platforms...
  - We should provide `navigator.memoryPressure` that returns a cached value. Use case: you want to change the behavior of how the page loads to improve user experience, etc.

~Related issue on exposing crashes: https://github.com/w3c/charter-webperf/issues/29

---

@mounirlamouri @yoavweiss as next steps, I propose we transfer the current proposal to WICG and move the related discussions there. WDYT?

**Comment by yoavweiss** [comment]
Sounds good to me!

**Comment by igrigorik** [comment]
A recap of activity on this front:
- https://github.com/w3c/device-memory/ — incubated and adopted by the group.
- https://github.com/WICG/memory-pressure/ — no active work, probably superseded by..
  - https://github.com/WICG/performance-memory/blob/master/explainer.md

**Comment by igrigorik** [comment]
Closing, please direct any related discussions to the relevant repos listed above.
